jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      env:
        - secure:  RSi6o05m8ZcgVr9a7TAQ6Ham/3D/zdqYeQG1ggMfK74fHuWJwFPNgAYwujZ7x9ce+kBw+YktKC00gyItX+h7iLbQ5wVmJgbHqUigDh+NbguFoi1HrCICvOFLlK2coyMf4Pq8jnOAMwQ70bJN2X0B2/Fzcm7tb+jQwa50zdgLtPGUR14YEokr74KysW1myjn+/tLQBxd2UtzBjXflqduHiKaaQSzZsUb1oQMcf/ckXdKlrY4qO7kRteESwDWCqXtWNsoSr8/LcR5UeNeeTslglM6TL+wBZVsMDgKlRiwiVzaPQ67afIqL2dox1a2n8stlN2uLGUfAJ+OBbqSOSBY+Xbj2mZQ/JSB38I7HcUJ+ZZFRS7RSZ6rNHaTC5alvyyUF11UKYxSA+aLSBauR1aW5LEBStK4Ug8h0FXNg/oeoayGSbk7bMUuQMdEMOEQNjDQr9c+BLl8YsLeCkix5IBO05PNw="
      script:
        - python hello_world.py
