jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      env:
        - secure: "JXcKlQXbXcB1DEql3SO4hHMh5Jq69NLhzdkxIZc/zEK0xMa7b/rMWRGna+c4euajFQCjWFoY4N6jtvOKhVJgI869S0aE/C0Pa80uOJEXLlHyuFpmYAwVS7pKKEwEgItA4B4GSGbLGpIK+VTBURfIf7tHLTJ7EBrI4QfVYwdbhQisecENGUdvolcR3LKDIS2th2HIdlbAoGW8D4gJNNF2ia5F0dwfqCAUNTQt1bjl3xKlUoc3iQe02jvI1f+sdAMGmrzMdElWfsFU23RbDlcK1TeCtAIRxHrw50Ri4cI461SeaOC3WewDK1kKsml4QuMGXJFC2DQqsCeFnQzUAN/fNAdoig0Pyxy36qEfJ+y2TMG9SIIQDq+oUXqiKR4edQ0KYKHiYZ80jp24bxkmhHvKoIMUAzNllRY+CoLbeAJAF0foAXN9Wdd/mjN7XNSSwsNlDWKagEKiaoqk2PnMOK2X+228ONhf+yNS6DjqWh/f1qD9B/i9Otde0hh3pZz7707lQ0sUKbXZPAkJ7H4cBPzoSLf/m33A7DaxvkgtoRa4jYtQ8Rtcq3ylmRa/Dv5VdXmbaDh35Hxc9OvclNy2kQTyMM89z/7hfKeFIBkckJ3+9ANoXietgxrfMhGvA8RIwS6Ltx9dKX8MdfhPHKFmdNwsnrnN/nLdhmtzPMTyIfLFePQ="
      script:
        - python hello_world.py
