jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      env:
        - secure: "dWukhfttTCyc6qTcJWIszNOWjkay/BXsCpw+kQb/rWtz0eGR1jhmUOZL9U5RTtX1a3z7OnHFDCr1+2efIhpD3aiIXLZQIHGpihJC1wkyOydluOSDFoR3sVfsw+lsC1KqwrVYAzR/TuWJLAuRDpFBuLsShbpzng6CFxdHIriy5b59rbjoFUOwK7sq9/IY89zwT+z9ISFrMaSMbg4PNl6sW2W3Hfn3Y8lhqCmO8qe5VDmz9ngIC0RAHcWnpz0/A0Ose5yrtU3sWKV5CIC0o3KdxYhujUl/YVZUbm29Q0xaitXqNYMEdko5ZeQz5KEGRZdjnTIOvXSs4bUORi1py4tCbQ/OyanbkyV039elZlJtG4lJt/zYvsWGk63E3m+mCjy5Erao6rriQ+1UjFEtumesZMrue/+SVR0FfhmKRkVp8+SzUY4Js0+50jtpBNOsQWByZPZiOhm8kC/6Nyax8UF+e+/UoaJPX9vtO3Vhpnz6D0s+QVDlpoKWXfV2Pr0R3Xy1LS72VmFKmZDcU264oR7EYWk3Vj6FKhiXYXkSKx8mszVX8B/9CjSEqlU15rOJnp3fLXrg/N3/71hvRZA034Nv5k435GBNeH/g5SV5/uqRErLd3CydgJ/XdJEZpeULKZhN1MtrCwmPcufsKXMjNlN7vsbe4gj1kIMvHkCgDDO14zY="
      script:
        - python hello_world.py
